version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - HOST=postgres
      - DBPORT=5432
      - PORT=8080
      - DBNAME=backend
      - USERNAME=backend
      - PASSWORD=backend
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
  postgres:
    image: postgres
    container_name: backend
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: